### ISSUE TITLE
Problem in http

### ISSUE THREAD

**Issue by LordSata** [Philiptpp/sonoff_registered_devices#2]
Hello, i'm interesting to obtain my data from ewelink app because of my 5 sonoff 4ch pro r2 i've only one backup firmware. I'm using a Ubuntu 18.04 LTS with pip installed and the requirements that you ask, but when i'm executing the script i obtain (i've have already installed http with: pip install http):

Traceback (most recent call last):
  File "sonoffDevices.py", line 2, in <module>
    from http import HTTPStatus
ImportError: cannot import name HTTPStatus

**Comment by tamasszadvari** [comment]
Use the pip3 instead of the normal pip to install the http-status component also, and use the python3 to execute the script. This is how I could make it work.
