### ISSUE TITLE
feature request - adding MAC + IP

### ISSUE THREAD

**Issue by camelcamro** [Philiptpp/sonoff_registered_devices#5]
Hello, if you can also add the MAC + IP, then it would be complet !!!!
great tool

1 more ... maybe you can give devel of *pysonofflanr3* also your link, as the APIKEY (API_KEY) is now supported and is much more easier to get the API KEYS as the tcpdump method at all ....
maybe he can update that to his WIKI to link each other ?

thx cu

**Comment by Philiptpp** [comment]
Added MAC ID to output. Since this script fetches the device info from sonoff cloud, the local IP information will not be available.
