### ISSUE TITLE
Credentials not accepted

### ISSUE THREAD

**Issue by mkafetzis** [Philiptpp/sonoff_registered_devices#8]
Hi, very nice utility. But the credentials is not accepted.
The error message i receive is : "Login failed! Please check credentials!"
I use Python 3.10.
Do you have in clue about this issue?
thanks.

**Comment by ardo911** [comment]
Hi, I'm experiencing exactly the same problem.

**Comment by warwickchapman** [comment]
Assuming there has been a change on the eWelink API side - this code has not been updated in 2 years.

**Comment by patbeirne** [comment]
I am also having this problem: May 2023

**Comment by Philiptpp** [comment]
Login issue has been fixed in latest commit.

**Comment by mkafetzis** [comment]
> Login issue has been fixed in latest commit.

i Confirm, it's working.
Thank you.

**Comment by heviiguy** [comment]
Another issue: I can't initialise it because...

"ModuleNotFoundError: No module named 'requests'"

Yet, I've installed the module:

```
Installing collected packages: wincertstore, uuid, chardet, urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2022.12.7 chardet-3.0.4 charset-normalizer-3.3.2 idna-2.8 requests-2.31.0 urllib3-1.26.5 uuid-1.30 wincertstore-0.2
```
Any suggestions, please?
